apiVersion: snorlax.moonbeam.nyc/v1beta1
kind: SleepSchedule
metadata:
  labels:
    app.kubernetes.io/name: sleepschedule
    app.kubernetes.io/instance: sleepschedule-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  namespace: default
  name: sleepschedule-sample
spec:
  dailyWindow:
    wakeTime: 7am
    sleepTime: 11pm
  timezone: America/New_York
  deploymentName: dummy-deployment
  wakeReplicas: 3
  ingressName: dummy-ingress